export type FieldDefinition = {
  id: string;
  name: string;
  category: string;
  source: string;
  summary: string;
  formula: string;
  misread: string;
  example?: string;
  tags: string[];
  relatedFieldIds: string[];
  toolRelevance: "high" | "medium" | "low";
  toolUsage?: string;
  drill?: string[];
};

export const fieldDefinitions: FieldDefinition[] = [
  {
    id: "gross-revenue",
    name: "营业额",
    category: "营业中心",
    source: "订单与门店经营数据",
    summary: "门店在选定日期内发生的经营流水，是经营规模口径，不是最终到账口径。",
    formula: "通常按订单原始金额汇总，需按业务场景确认是否含退款、优惠、配送费、平台补贴。",
    misread: "客户容易把营业额理解成银行卡到账金额。实际上平台扣点、退款、活动和账期都会让两者不同。",
    example: "5 月 1 日营业额 3000 元，不代表 5 月 2 日银行卡一定到账 3000 元。",
    tags: ["经营", "订单", "当前工具相关"],
    relatedFieldIds: ["settlement-amount", "arrival-amount", "gross-profit-revenue"],
    toolRelevance: "high",
    toolUsage: "用于确认本次核算的经营发生周期，但不直接等同于到卡金额。",
    drill: ["确认统计时间字段", "按订单状态筛选", "区分外卖订单和团购核销订单"],
  },
  {
    id: "order-count",
    name: "订单数",
    category: "营业中心",
    source: "订单明细",
    summary: "选定时间内的订单量，用于观察经营规模和接单活跃度。",
    formula: "按订单创建、支付、完成或核销时间统计时，结果可能不同。",
    misread: "不同页面若时间口径不同，会出现订单数不一致。团购核销尤其要区分购买日和核销日。",
    tags: ["经营", "订单"],
    relatedFieldIds: ["gross-revenue"],
    toolRelevance: "low",
  },
  {
    id: "refund-amount",
    name: "退款金额",
    category: "营业中心",
    source: "退款订单 / 逆向交易",
    summary: "已发生退款或冲销的金额，会影响净营收和后续平台结算。",
    formula: "退款金额按退款成功时间或原订单时间统计时，会影响当日数据。",
    misread: "退款不一定与原订单同日入账或冲销，客户会看到营业额在某天高、入账在另一天下降。",
    tags: ["退款", "结算", "异常"],
    relatedFieldIds: ["net-revenue", "settlement-amount", "arrival-amount"],
    toolRelevance: "medium",
  },
  {
    id: "net-revenue",
    name: "净营收",
    category: "营业中心",
    source: "经营汇总",
    summary: "扣除退款、优惠或部分成本后的经营收入观察值。",
    formula: "常见口径：营业额 - 退款 - 商家承担优惠。是否扣平台佣金需按页面定义确认。",
    misread: "净营收不一定等于财务中心业务收入，也不一定等于可提现余额。",
    tags: ["经营", "退款", "收入"],
    relatedFieldIds: ["gross-revenue", "refund-amount", "business-income"],
    toolRelevance: "medium",
  },
  {
    id: "estimated-income",
    name: "预计收入",
    category: "营业中心",
    source: "平台推送 / 订单估算",
    summary: "平台或系统按当前订单状态估算的可收入金额，适合经营参考。",
    formula: "订单金额 - 预计平台扣点 - 预计退款或优惠。实际结算以后可能变化。",
    misread: "预计收入不是已到账。未核销团购、未结算订单、平台补贴延后都会改变最终金额。",
    tags: ["经营", "预估", "结算"],
    relatedFieldIds: ["settlement-amount", "arrival-amount"],
    toolRelevance: "medium",
  },
  {
    id: "booking-amount",
    name: "入账金额",
    category: "营业中心",
    source: "平台结算 / 支付通道 / 银行流水",
    summary: "资金进入平台账户、分账账户或银行账户的金额，是资金侧口径。",
    formula: "平台结算金额或通道入账金额，通常已受平台佣金、退款、账期和扣款影响。",
    misread: "入账金额大于或小于账单金额都可能出现，需要看是否账单缺失、跨账期、负向退款或门店绑定异常。",
    tags: ["资金/到账", "结算", "当前工具相关"],
    relatedFieldIds: ["arrival-amount", "settlement-amount", "actual-received"],
    toolRelevance: "high",
    toolUsage: "用于解释平台资金已经进入某个账户层，但不一定已经到银行卡。",
  },
  {
    id: "reconciliation-status",
    name: "对账状态",
    category: "营业中心",
    source: "食亨对账流程",
    summary: "表示平台账单、订单、入账流水之间是否完成匹配。",
    formula: "常见状态包含待对账、已对账、异常、待分账、已分账。",
    misread: "待对账不等于没钱，可能是账单未同步、门店未绑定、短 ID 未映射或存在负数账单。",
    tags: ["对账/异常", "状态"],
    relatedFieldIds: ["booking-amount", "manual-write-off"],
    toolRelevance: "medium",
  },
  {
    id: "finance-period",
    name: "账期",
    category: "财务中心",
    source: "财务做账页面",
    summary: "财务按自然月或业务规则归集应收、实收和未收的期间。",
    formula: "系统常用 YYYY-MM，例如 2026-02。页面数据可能每小时同步一次。",
    misread: "客户说的账期通常是平台打款周期，财务中心账期通常是做账归属月份，两者不是同一概念。",
    tags: ["账期", "财务", "当前工具相关"],
    relatedFieldIds: ["platform-term-days", "arrival-date"],
    toolRelevance: "high",
    toolUsage: "本工具里的 T+N 是平台打款周期，不是财务中心自然月账期。",
  },
  {
    id: "receivable-income",
    name: "应收收入",
    category: "财务中心",
    source: "多业务线账单",
    summary: "按权责发生制确认的应收金额，账单生成时即可形成。",
    formula: "支付/提现服务费来自分账宽表；外卖接单费来自后付费账单和预付费消耗；渠道佣金来自对应业务系统。",
    misread: "应收不是已经收到的钱。账单已生成但未终结时，应收可能大于业务收入。",
    tags: ["财务", "收入", "应收"],
    relatedFieldIds: ["business-income", "actual-received", "unreceived-amount"],
    toolRelevance: "medium",
  },
  {
    id: "business-income",
    name: "业务收入",
    category: "财务中心",
    source: "已终结或已确认账单",
    summary: "更接近业务已经确认可计入的收入，用于计算未收金额的基准。",
    formula: "多数业务线与应收一致；部分渠道佣金或外卖接单费会因终结状态和数据源不同而不一致。",
    misread: "业务收入为 0 时，系统可能回退用应收作为未收计算基准。",
    tags: ["财务", "收入"],
    relatedFieldIds: ["receivable-income", "unreceived-amount"],
    toolRelevance: "medium",
  },
  {
    id: "actual-received",
    name: "实收金额",
    category: "财务中心",
    source: "系统获取 + 财务录入",
    summary: "财务实际收到或确认收到的金额，支持多次累计录入。",
    formula: "实收金额 = 系统自动获取金额 + 财务手动录入金额。",
    misread: "录入一笔实收不代表整条业务线完结，若子账号、渠道或模式还有余额未录入，仍会显示未收。",
    tags: ["财务", "资金/到账", "当前工具相关"],
    relatedFieldIds: ["booking-amount", "arrival-amount", "unreceived-amount"],
    toolRelevance: "high",
  },
  {
    id: "unreceived-amount",
    name: "未收金额",
    category: "财务中心",
    source: "前端实时计算",
    summary: "当前还未被实收覆盖的金额，用于跟进收款缺口。",
    formula: "未收金额 = 业务收入 - 实收金额；完结或手动抹平后显示为 0。",
    misread: "未收不一定是客户欠款，也可能是平台未结算、银行未到账、跨账期或数据未同步。",
    tags: ["财务", "对账/异常"],
    relatedFieldIds: ["business-income", "actual-received", "manual-write-off"],
    toolRelevance: "medium",
  },
  {
    id: "collection-health",
    name: "收款健康度",
    category: "财务中心",
    source: "财务做账汇总",
    summary: "用来快速判断本期收款进度是否健康。",
    formula: "收款健康度 = 实收金额 / 应收收入 x 100%。95% 以上通常较健康，80% 以下需重点跟进。",
    misread: "健康度低不一定是坏账，可能只是平台账期未到或客户按合同月结。",
    tags: ["财务", "指标"],
    relatedFieldIds: ["receivable-income", "actual-received"],
    toolRelevance: "low",
  },
  {
    id: "payment-service-fee",
    name: "支付服务费",
    category: "财务中心",
    source: "分账宽表 middle_brand_extend_dashboard",
    summary: "平台或通道支付交易产生的服务费收入。",
    formula: "常见口径为 SUM(p_real_fee_amt)，按内部商户号拆分。",
    misread: "支付服务费与提现服务费经常被混用。支付服务费跟交易支付有关，提现服务费跟提现动作有关。",
    tags: ["服务费/佣金", "财务"],
    relatedFieldIds: ["withdraw-service-fee"],
    toolRelevance: "medium",
  },
  {
    id: "withdraw-service-fee",
    name: "提现服务费",
    category: "财务中心",
    source: "分账宽表 / 服务费账单",
    summary: "商户提现时产生的服务费收入。",
    formula: "常见口径为 SUM(w_real_fee_amt)，按内部商户号拆分。",
    misread: "有余额但没提现时，不一定产生提现服务费；提现失败也可能导致实收节奏不同。",
    tags: ["服务费/佣金", "余额/提现"],
    relatedFieldIds: ["payment-service-fee", "withdrawable-balance"],
    toolRelevance: "medium",
  },
  {
    id: "takeout-order-fee",
    name: "外卖接单费",
    category: "财务中心",
    source: "shop_account_bill / 服务费账单",
    summary: "外卖接单按单量或服务规则产生的收入，常拆成后付费和预充值模式。",
    formula: "总实收常见为单量消耗 x 0.01；三种模式为后付费总部承担、后付费门店承担、预充值门店承担。",
    misread: "客户常把平台外卖佣金和食亨外卖接单费混在一起，解释时要分清平台扣点与食亨服务费。",
    tags: ["服务费/佣金", "外卖", "财务"],
    relatedFieldIds: ["platform-commission-rate", "payment-service-fee"],
    toolRelevance: "medium",
  },
  {
    id: "ordering-channel-commission",
    name: "渠道佣金(订货)",
    category: "财务中心",
    source: "v_erp_brand_voucher / 氚云",
    summary: "订货业务支付渠道产生的佣金收入。",
    formula: "按微信支付、微企付、B2B 支付、收钱吧等渠道分别计算，费率按渠道规则。",
    misread: "某渠道显示 0 可能是氚云尚未同步，不一定是没有收入。",
    tags: ["服务费/佣金", "订阅/台账"],
    relatedFieldIds: ["ledger-id"],
    toolRelevance: "medium",
  },
  {
    id: "smart-store-channel-commission",
    name: "渠道佣金(智慧门店)",
    category: "财务中心",
    source: "氚云相关表单",
    summary: "智慧门店业务支付渠道产生的佣金收入。",
    formula: "按微信、支付宝、收钱吧返佣等渠道汇总。",
    misread: "同叫渠道佣金，但订货和智慧门店的数据来源不同，不能直接合并解释。",
    tags: ["服务费/佣金", "智慧门店"],
    relatedFieldIds: ["ordering-channel-commission"],
    toolRelevance: "medium",
  },
  {
    id: "bank-float-income",
    name: "银行沉淀收益",
    category: "财务中心",
    source: "分账账户余额",
    summary: "资金在银行账户沉淀期间形成的利息类收益。",
    formula: "余额 x 年化利率 / 365。苏商、新网等银行利率规则不同，网商银行通常不参与该口径。",
    misread: "这不是客户订单收入，而是资金沉淀收益，不能拿来解释营业额差异。",
    tags: ["余额/提现", "财务"],
    relatedFieldIds: ["withdrawable-balance"],
    toolRelevance: "low",
  },
  {
    id: "withdrawable-balance",
    name: "可提现余额",
    category: "财务中心",
    source: "分账账户 / 银行账户",
    summary: "扣除冻结、在途、待对账等限制后，可发起提现的余额。",
    formula: "账户余额 - 冻结金额 - 在途金额 - 不可提现限制金额。",
    misread: "账户余额、可提现余额、实收金额是三个字段。余额可见不代表可以提现，也不代表财务已实收。",
    tags: ["余额/提现", "资金/到账", "当前工具相关"],
    relatedFieldIds: ["actual-received", "withdraw-service-fee"],
    toolRelevance: "high",
  },
  {
    id: "manual-write-off",
    name: "手动抹平差异",
    category: "财务中心",
    source: "财务做账操作记录",
    summary: "财务确认差异无需继续追收时，用备注把差异完结。",
    formula: "完结后未收显示为 0，原始差异和备注保留在操作历史中。",
    misread: "抹平不是删除差异，而是用审计记录说明为什么接受差异。",
    tags: ["对账/异常", "财务"],
    relatedFieldIds: ["unreceived-amount", "reconciliation-status"],
    toolRelevance: "low",
  },
  {
    id: "ledger-id",
    name: "ledger_id",
    category: "财务中心",
    source: "订阅系统与氚云对账",
    summary: "订阅系统中用于关联氚云台账序号的关键字段。",
    formula: "subscriptions.ledger_id 对应氚云台账序号。为空时可能进入待补录状态。",
    misread: "ledger_id 缺失会让两边都有数据却无法自动匹配，表现为对账差异。",
    tags: ["订阅/台账", "对账/异常"],
    relatedFieldIds: ["ordering-channel-commission"],
    toolRelevance: "low",
  },
  {
    id: "settlement-amount",
    name: "结算金额",
    category: "轻量核算",
    source: "用户手动录入的平台结算数据",
    summary: "平台在当前营业周期内准备结算给门店或商户的金额，是本工具计算到卡金额的起点。",
    formula: "门店预计到卡金额 = 结算金额 - 品牌抽佣金额。",
    misread: "结算金额不一定等于营业额，也不一定等于银行卡最终到账金额，需结合平台账期、佣金、退款和其他扣款理解。",
    tags: ["资金/到账", "结算", "当前工具相关"],
    relatedFieldIds: ["gross-revenue", "platform-commission-amount", "arrival-amount"],
    toolRelevance: "high",
    toolUsage: "用户在每个平台卡片中录入，用来计算该平台的门店预计到卡金额。",
  },
  {
    id: "arrival-amount",
    name: "到卡金额",
    category: "轻量核算",
    source: "本工具按录入项实时计算",
    summary: "扣除品牌抽佣后，预计进入门店银行卡的金额。",
    formula: "到卡金额 = 结算金额 - 品牌抽佣金额。",
    misread: "到卡金额是轻量估算结果，不等同于银行流水实收。实际到账还可能受平台调整、节假日和异常扣款影响。",
    tags: ["资金/到账", "当前工具相关"],
    relatedFieldIds: ["settlement-amount", "arrival-date", "actual-received"],
    toolRelevance: "high",
    toolUsage: "展示在看板、列表、日历和底部汇总中。",
  },
  {
    id: "arrival-date",
    name: "预计到卡日期",
    category: "轻量核算",
    source: "本工具按营业结束日期和账期天数计算",
    summary: "按平台 T+N 规则推算的预计银行卡到账日期。",
    formula: "预计到卡日期 = 营业结束日期 + 平台账期天数。",
    misread: "首版按自然日计算，不跳过周末和节假日；如果平台有特殊结算日，需人工调整账期天数。",
    tags: ["账期", "资金/到账", "当前工具相关"],
    relatedFieldIds: ["platform-term-days", "business-end-date", "arrival-amount"],
    toolRelevance: "high",
    toolUsage: "用于结果区分组、筛选和日历展示。",
  },
  {
    id: "business-start-date",
    name: "营业开始日期",
    category: "轻量核算",
    source: "用户手动录入",
    summary: "本次核算覆盖的经营开始日期。",
    formula: "与营业结束日期共同定义经营周期。",
    misread: "营业日期是经营发生日，不是平台打款日，也不是财务中心做账月份。",
    tags: ["经营", "日期", "当前工具相关"],
    relatedFieldIds: ["business-end-date", "arrival-date"],
    toolRelevance: "high",
  },
  {
    id: "business-end-date",
    name: "营业结束日期",
    category: "轻量核算",
    source: "用户手动录入",
    summary: "本次核算覆盖的经营结束日期，也是首版预计到卡日期计算的基准日期。",
    formula: "预计到卡日期 = 营业结束日期 + 平台账期天数。",
    misread: "结束日期不能早于开始日期。不要用实际到账日反填营业结束日期。",
    tags: ["经营", "日期", "当前工具相关"],
    relatedFieldIds: ["business-start-date", "platform-term-days", "arrival-date"],
    toolRelevance: "high",
  },
  {
    id: "platform-term-days",
    name: "平台账期天数",
    category: "轻量核算",
    source: "平台默认规则 + 用户手动调整",
    summary: "平台从经营结束日到预计到卡日之间的自然日间隔。",
    formula: "T+N 中的 N 即账期天数。",
    misread: "这里的账期是平台打款周期，不是财务中心账期。不同平台或特殊合同可能有不同 T+N。",
    tags: ["账期", "当前工具相关"],
    relatedFieldIds: ["finance-period", "arrival-date"],
    toolRelevance: "high",
  },
  {
    id: "platform-commission-rate",
    name: "品牌抽佣比例",
    category: "轻量核算",
    source: "用户手动录入",
    summary: "品牌从结算金额中抽取的比例，用于估算门店实得。",
    formula: "品牌抽佣金额 = 结算金额 x 品牌抽佣比例。",
    misread: "品牌抽佣不是平台佣金，也不是食亨服务费。它是本工具为了轻量核算门店到卡而单独录入的比例。",
    tags: ["服务费/佣金", "当前工具相关"],
    relatedFieldIds: ["platform-commission-amount", "settlement-amount"],
    toolRelevance: "high",
  },
  {
    id: "platform-commission-amount",
    name: "品牌抽佣金额",
    category: "轻量核算",
    source: "本工具按结算金额和抽佣比例计算",
    summary: "品牌从当前平台结算金额中扣出的金额。",
    formula: "品牌抽佣金额 = 结算金额 x 品牌抽佣比例。",
    misread: "不要与平台外卖佣金混用。平台佣金通常已影响平台结算金额，品牌抽佣是结算后再分给门店前的内部扣减。",
    tags: ["服务费/佣金", "当前工具相关"],
    relatedFieldIds: ["platform-commission-rate", "arrival-amount"],
    toolRelevance: "high",
  },
];

