export type FieldDefinition = {
  id: string;
  name: string;
  category: string;
  source: string;
  summary: string;
  formula: string;
  misread: string;
  example?: string;
  tags: string[];
  relatedFieldIds: string[];
  toolRelevance: "high" | "medium" | "low";
  toolUsage?: string;
  drill?: string[];
};

export const fieldDefinitions: FieldDefinition[] = [
  {
    id: "gross-revenue",
    name: "营业额",
    category: "营业中心",
    source: "订单与门店经营数据",
    summary: "门店在选定日期内发生的经营流水，是经营规模口径，不是最终到账口径。",
    formula: "通常按订单原始金额汇总，需按业务场景确认是否含退款、优惠、配送费、平台补贴；在智慧门店营收看板中用于对比预计收入和商家支出。",
    misread: "客户容易把营业额理解成银行卡到账金额。实际上平台扣点、退款、优惠、商家支出和账期都会让两者不同。",
    example: "5 月 1 日营业额 3000 元，不代表 5 月 2 日银行卡一定到账 3000 元；智慧门店看板中也不等同于预计收入。",
    tags: ["经营", "订单", "智慧门店", "营收看板", "当前工具相关"],
    relatedFieldIds: ["settlement-amount", "arrival-amount", "gross-profit-revenue"],
    toolRelevance: "high",
    toolUsage: "用于确认本次核算的经营发生周期，但不直接等同于到卡金额。",
    drill: ["确认统计时间字段", "按订单状态筛选", "区分外卖订单和团购核销订单"],
  },
  {
    id: "order-count",
    name: "订单数",
    category: "营业中心",
    source: "订单明细",
    summary: "选定时间内的订单量，用于观察经营规模和接单活跃度；智慧门店营收看板中截图字段为“有效订单数”。",
    formula: "按订单创建、支付、完成或核销时间统计时，结果可能不同；有效订单数通常会排除无效、取消或未满足统计条件的订单。",
    misread: "不同页面若时间口径或有效订单筛选规则不同，会出现订单数不一致。团购核销尤其要区分购买日和核销日。",
    tags: ["经营", "订单", "智慧门店", "营收看板"],
    relatedFieldIds: ["gross-revenue"],
    toolRelevance: "low",
  },
  {
    id: "refund-amount",
    name: "退款金额",
    category: "营业中心",
    source: "退款订单 / 逆向交易",
    summary: "已发生退款或冲销的金额，会影响净营收和后续平台结算；智慧门店营收看板中截图字段为“部分退款金额”。",
    formula: "退款金额按退款成功时间或原订单时间统计时，会影响当日数据；部分退款金额通常只统计订单部分金额被退回的逆向交易。",
    misread: "退款不一定与原订单同日入账或冲销，客户会看到营业额在某天高、入账在另一天下降；部分退款不代表整单取消。",
    tags: ["退款", "结算", "异常", "智慧门店", "营收看板"],
    relatedFieldIds: ["net-revenue", "settlement-amount", "arrival-amount"],
    toolRelevance: "medium",
  },
  {
    id: "net-revenue",
    name: "净营收",
    category: "营业中心",
    source: "经营汇总",
    summary: "扣除退款、优惠或部分成本后的经营收入观察值。",
    formula: "常见口径：营业额 - 退款 - 商家承担优惠。是否扣平台佣金需按页面定义确认。",
    misread: "净营收不一定等于财务中心业务收入，也不一定等于可提现余额。",
    tags: ["经营", "退款", "收入"],
    relatedFieldIds: ["gross-revenue", "refund-amount", "business-income"],
    toolRelevance: "medium",
  },
  {
    id: "estimated-income",
    name: "预计收入",
    category: "营业中心",
    source: "平台推送 / 订单估算 / 食亨智慧门店 APP 营收看板",
    summary: "平台或系统按当前订单状态估算的可收入金额，适合经营参考；智慧门店营收看板中作为核心汇总指标展示。",
    formula: "通常由营业额扣减商家支出、退款、优惠、平台服务费等影响项后估算，实际口径以智慧门店看板说明为准。",
    misread: "预计收入不是已到账，也不是银行卡实收。未核销团购、未结算订单、平台补贴延后、部分退款和费用调整都会改变最终金额。",
    tags: ["经营", "预估", "结算", "智慧门店", "营收看板"],
    relatedFieldIds: ["settlement-amount", "arrival-amount"],
    toolRelevance: "medium",
  },
  {
    id: "booking-amount",
    name: "入账金额",
    category: "营业中心",
    source: "平台结算 / 支付通道 / 银行流水",
    summary: "资金进入平台账户、分账账户或银行账户的金额，是资金侧口径。",
    formula: "平台结算金额或通道入账金额，通常已受平台佣金、退款、账期和扣款影响。",
    misread: "入账金额大于或小于账单金额都可能出现，需要看是否账单缺失、跨账期、负向退款或门店绑定异常。",
    tags: ["资金/到账", "结算", "当前工具相关"],
    relatedFieldIds: ["arrival-amount", "settlement-amount", "actual-received"],
    toolRelevance: "high",
    toolUsage: "用于解释平台资金已经进入某个账户层，但不一定已经到银行卡。",
  },
  {
    id: "reconciliation-status",
    name: "对账状态",
    category: "营业中心",
    source: "食亨对账流程",
    summary: "表示平台账单、订单、入账流水之间是否完成匹配。",
    formula: "常见状态包含待对账、已对账、异常、待分账、已分账。",
    misread: "待对账不等于没钱，可能是账单未同步、门店未绑定、短 ID 未映射或存在负数账单。",
    tags: ["对账/异常", "状态"],
    relatedFieldIds: ["booking-amount", "manual-write-off"],
    toolRelevance: "medium",
  },
  {
    id: "finance-period",
    name: "账期",
    category: "财务中心",
    source: "财务做账页面",
    summary: "财务按自然月或业务规则归集应收、实收和未收的期间。",
    formula: "系统常用 YYYY-MM，例如 2026-02。页面数据可能每小时同步一次。",
    misread: "客户说的账期通常是平台打款周期，财务中心账期通常是做账归属月份，两者不是同一概念。",
    tags: ["账期", "财务", "当前工具相关"],
    relatedFieldIds: ["platform-term-days", "arrival-date"],
    toolRelevance: "high",
    toolUsage: "本工具里的 T+N 是平台打款周期，不是财务中心自然月账期。",
  },
  {
    id: "receivable-income",
    name: "应收收入",
    category: "财务中心",
    source: "多业务线账单",
    summary: "按权责发生制确认的应收金额，账单生成时即可形成。",
    formula: "支付/提现服务费来自分账宽表；外卖接单费来自后付费账单和预付费消耗；渠道佣金来自对应业务系统。",
    misread: "应收不是已经收到的钱。账单已生成但未终结时，应收可能大于业务收入。",
    tags: ["财务", "收入", "应收"],
    relatedFieldIds: ["business-income", "actual-received", "unreceived-amount"],
    toolRelevance: "medium",
  },
  {
    id: "business-income",
    name: "业务收入",
    category: "财务中心",
    source: "已终结或已确认账单",
    summary: "更接近业务已经确认可计入的收入，用于计算未收金额的基准。",
    formula: "多数业务线与应收一致；部分渠道佣金或外卖接单费会因终结状态和数据源不同而不一致。",
    misread: "业务收入为 0 时，系统可能回退用应收作为未收计算基准。",
    tags: ["财务", "收入"],
    relatedFieldIds: ["receivable-income", "unreceived-amount"],
    toolRelevance: "medium",
  },
  {
    id: "actual-received",
    name: "实收金额",
    category: "财务中心",
    source: "系统获取 + 财务录入",
    summary: "财务实际收到或确认收到的金额，支持多次累计录入。",
    formula: "实收金额 = 系统自动获取金额 + 财务手动录入金额。",
    misread: "录入一笔实收不代表整条业务线完结，若子账号、渠道或模式还有余额未录入，仍会显示未收。",
    tags: ["财务", "资金/到账", "当前工具相关"],
    relatedFieldIds: ["booking-amount", "arrival-amount", "unreceived-amount"],
    toolRelevance: "high",
  },
  {
    id: "unreceived-amount",
    name: "未收金额",
    category: "财务中心",
    source: "前端实时计算",
    summary: "当前还未被实收覆盖的金额，用于跟进收款缺口。",
    formula: "未收金额 = 业务收入 - 实收金额；完结或手动抹平后显示为 0。",
    misread: "未收不一定是客户欠款，也可能是平台未结算、银行未到账、跨账期或数据未同步。",
    tags: ["财务", "对账/异常"],
    relatedFieldIds: ["business-income", "actual-received", "manual-write-off"],
    toolRelevance: "medium",
  },
  {
    id: "collection-health",
    name: "收款健康度",
    category: "财务中心",
    source: "财务做账汇总",
    summary: "用来快速判断本期收款进度是否健康。",
    formula: "收款健康度 = 实收金额 / 应收收入 x 100%。95% 以上通常较健康，80% 以下需重点跟进。",
    misread: "健康度低不一定是坏账，可能只是平台账期未到或客户按合同月结。",
    tags: ["财务", "指标"],
    relatedFieldIds: ["receivable-income", "actual-received"],
    toolRelevance: "low",
  },
  {
    id: "payment-service-fee",
    name: "支付服务费",
    category: "财务中心",
    source: "分账宽表 middle_brand_extend_dashboard",
    summary: "平台或通道支付交易产生的服务费收入。",
    formula: "常见口径为 SUM(p_real_fee_amt)，按内部商户号拆分。",
    misread: "支付服务费与提现服务费经常被混用。支付服务费跟交易支付有关，提现服务费跟提现动作有关。",
    tags: ["服务费/佣金", "财务"],
    relatedFieldIds: ["withdraw-service-fee"],
    toolRelevance: "medium",
  },
  {
    id: "withdraw-service-fee",
    name: "提现服务费",
    category: "财务中心",
    source: "分账宽表 / 服务费账单",
    summary: "商户提现时产生的服务费收入。",
    formula: "常见口径为 SUM(w_real_fee_amt)，按内部商户号拆分。",
    misread: "有余额但没提现时，不一定产生提现服务费；提现失败也可能导致实收节奏不同。",
    tags: ["服务费/佣金", "余额/提现"],
    relatedFieldIds: ["payment-service-fee", "withdrawable-balance"],
    toolRelevance: "medium",
  },
  {
    id: "takeout-order-fee",
    name: "外卖接单费",
    category: "财务中心",
    source: "shop_account_bill / 服务费账单",
    summary: "外卖接单按单量或服务规则产生的收入，常拆成后付费和预充值模式。",
    formula: "总实收常见为单量消耗 x 0.01；三种模式为后付费总部承担、后付费门店承担、预充值门店承担。",
    misread: "客户常把平台外卖佣金和食亨外卖接单费混在一起，解释时要分清平台扣点与食亨服务费。",
    tags: ["服务费/佣金", "外卖", "财务"],
    relatedFieldIds: ["platform-commission-rate", "payment-service-fee"],
    toolRelevance: "medium",
  },
  {
    id: "ordering-channel-commission",
    name: "渠道佣金(订货)",
    category: "财务中心",
    source: "v_erp_brand_voucher / 氚云",
    summary: "订货业务支付渠道产生的佣金收入。",
    formula: "按微信支付、微企付、B2B 支付、收钱吧等渠道分别计算，费率按渠道规则。",
    misread: "某渠道显示 0 可能是氚云尚未同步，不一定是没有收入。",
    tags: ["服务费/佣金", "订阅/台账"],
    relatedFieldIds: ["ledger-id"],
    toolRelevance: "medium",
  },
  {
    id: "smart-store-channel-commission",
    name: "渠道佣金(智慧门店)",
    category: "财务中心",
    source: "氚云相关表单",
    summary: "智慧门店业务支付渠道产生的佣金收入。",
    formula: "按微信、支付宝、收钱吧返佣等渠道汇总。",
    misread: "同叫渠道佣金，但订货和智慧门店的数据来源不同，不能直接合并解释。",
    tags: ["服务费/佣金", "智慧门店"],
    relatedFieldIds: ["ordering-channel-commission"],
    toolRelevance: "medium",
  },
  {
    id: "bank-float-income",
    name: "银行沉淀收益",
    category: "财务中心",
    source: "分账账户余额",
    summary: "资金在银行账户沉淀期间形成的利息类收益。",
    formula: "余额 x 年化利率 / 365。苏商、新网等银行利率规则不同，网商银行通常不参与该口径。",
    misread: "这不是客户订单收入，而是资金沉淀收益，不能拿来解释营业额差异。",
    tags: ["余额/提现", "财务"],
    relatedFieldIds: ["withdrawable-balance"],
    toolRelevance: "low",
  },
  {
    id: "withdrawable-balance",
    name: "可提现余额",
    category: "财务中心",
    source: "分账账户 / 银行账户",
    summary: "扣除冻结、在途、待对账等限制后，可发起提现的余额。",
    formula: "账户余额 - 冻结金额 - 在途金额 - 不可提现限制金额。",
    misread: "账户余额、可提现余额、实收金额是三个字段。余额可见不代表可以提现，也不代表财务已实收。",
    tags: ["余额/提现", "资金/到账", "当前工具相关"],
    relatedFieldIds: ["actual-received", "withdraw-service-fee"],
    toolRelevance: "high",
  },
  {
    id: "manual-write-off",
    name: "手动抹平差异",
    category: "财务中心",
    source: "财务做账操作记录",
    summary: "财务确认差异无需继续追收时，用备注把差异完结。",
    formula: "完结后未收显示为 0，原始差异和备注保留在操作历史中。",
    misread: "抹平不是删除差异，而是用审计记录说明为什么接受差异。",
    tags: ["对账/异常", "财务"],
    relatedFieldIds: ["unreceived-amount", "reconciliation-status"],
    toolRelevance: "low",
  },
  {
    id: "ledger-id",
    name: "ledger_id",
    category: "财务中心",
    source: "订阅系统与氚云对账",
    summary: "订阅系统中用于关联氚云台账序号的关键字段。",
    formula: "subscriptions.ledger_id 对应氚云台账序号。为空时可能进入待补录状态。",
    misread: "ledger_id 缺失会让两边都有数据却无法自动匹配，表现为对账差异。",
    tags: ["订阅/台账", "对账/异常"],
    relatedFieldIds: ["ordering-channel-commission"],
    toolRelevance: "low",
  },
  {
    id: "settlement-amount",
    name: "结算金额",
    category: "轻量核算",
    source: "用户手动录入的平台结算数据",
    summary: "平台在当前营业周期内准备结算给门店或商户的金额，是本工具计算到卡金额的起点。",
    formula: "门店预计到卡金额 = 结算金额 - 品牌抽佣金额。",
    misread: "结算金额不一定等于营业额，也不一定等于银行卡最终到账金额，需结合平台账期、佣金、退款和其他扣款理解。",
    tags: ["资金/到账", "结算", "当前工具相关"],
    relatedFieldIds: ["gross-revenue", "platform-commission-amount", "arrival-amount"],
    toolRelevance: "high",
    toolUsage: "用户在每个平台卡片中录入，用来计算该平台的门店预计到卡金额。",
  },
  {
    id: "arrival-amount",
    name: "到卡金额",
    category: "轻量核算",
    source: "本工具按录入项实时计算",
    summary: "扣除品牌抽佣后，预计进入门店银行卡的金额。",
    formula: "到卡金额 = 结算金额 - 品牌抽佣金额。",
    misread: "到卡金额是轻量估算结果，不等同于银行流水实收。实际到账还可能受平台调整、节假日和异常扣款影响。",
    tags: ["资金/到账", "当前工具相关"],
    relatedFieldIds: ["settlement-amount", "arrival-date", "actual-received"],
    toolRelevance: "high",
    toolUsage: "展示在看板、列表、日历和底部汇总中。",
  },
  {
    id: "arrival-date",
    name: "预计到卡日期",
    category: "轻量核算",
    source: "本工具按营业结束日期和账期天数计算",
    summary: "按平台 T+N 规则推算的预计银行卡到账日期。",
    formula: "预计到卡日期 = 营业结束日期 + 平台账期天数。",
    misread: "首版按自然日计算，不跳过周末和节假日；如果平台有特殊结算日，需人工调整账期天数。",
    tags: ["账期", "资金/到账", "当前工具相关"],
    relatedFieldIds: ["platform-term-days", "business-end-date", "arrival-amount"],
    toolRelevance: "high",
    toolUsage: "用于结果区分组、筛选和日历展示。",
  },
  {
    id: "business-start-date",
    name: "营业开始日期",
    category: "轻量核算",
    source: "用户手动录入",
    summary: "本次核算覆盖的经营开始日期。",
    formula: "与营业结束日期共同定义经营周期。",
    misread: "营业日期是经营发生日，不是平台打款日，也不是财务中心做账月份。",
    tags: ["经营", "日期", "当前工具相关"],
    relatedFieldIds: ["business-end-date", "arrival-date"],
    toolRelevance: "high",
  },
  {
    id: "business-end-date",
    name: "营业结束日期",
    category: "轻量核算",
    source: "用户手动录入",
    summary: "本次核算覆盖的经营结束日期，也是首版预计到卡日期计算的基准日期。",
    formula: "预计到卡日期 = 营业结束日期 + 平台账期天数。",
    misread: "结束日期不能早于开始日期。不要用实际到账日反填营业结束日期。",
    tags: ["经营", "日期", "当前工具相关"],
    relatedFieldIds: ["business-start-date", "platform-term-days", "arrival-date"],
    toolRelevance: "high",
  },
  {
    id: "platform-term-days",
    name: "平台账期天数",
    category: "轻量核算",
    source: "平台默认规则 + 用户手动调整",
    summary: "平台从经营结束日到预计到卡日之间的自然日间隔。",
    formula: "T+N 中的 N 即账期天数。",
    misread: "这里的账期是平台打款周期，不是财务中心账期。不同平台或特殊合同可能有不同 T+N。",
    tags: ["账期", "当前工具相关"],
    relatedFieldIds: ["finance-period", "arrival-date"],
    toolRelevance: "high",
  },
  {
    id: "platform-commission-rate",
    name: "品牌抽佣比例",
    category: "轻量核算",
    source: "用户手动录入",
    summary: "品牌从结算金额中抽取的比例，用于估算门店实得。",
    formula: "品牌抽佣金额 = 结算金额 x 品牌抽佣比例。",
    misread: "品牌抽佣不是平台佣金，也不是食亨服务费。它是本工具为了轻量核算门店到卡而单独录入的比例。",
    tags: ["服务费/佣金", "当前工具相关"],
    relatedFieldIds: ["platform-commission-amount", "settlement-amount"],
    toolRelevance: "high",
  },
  {
    id: "platform-commission-amount",
    name: "品牌抽佣金额",
    category: "轻量核算",
    source: "本工具按结算金额和抽佣比例计算",
    summary: "品牌从当前平台结算金额中扣出的金额。",
    formula: "品牌抽佣金额 = 结算金额 x 品牌抽佣比例。",
    misread: "不要与平台外卖佣金混用。平台佣金通常已影响平台结算金额，品牌抽佣是结算后再分给门店前的内部扣减。",
    tags: ["服务费/佣金", "当前工具相关"],
    relatedFieldIds: ["platform-commission-rate", "arrival-amount"],
    toolRelevance: "high",
  },
  {
    id: "smart-store-merchant-expense",
    name: "商家支出",
    category: "智慧门店",
    source: "食亨智慧门店 APP - 经营 - 营收 - 核心指标",
    summary: "商家侧为订单承担的支出汇总，用于解释营业额与预计收入之间的扣减差异。",
    formula: "通常由优惠、服务费、配送相关费用、退款或其他商家承担项汇总形成，具体以智慧门店营收看板口径为准。",
    misread: "商家支出不是平台打款金额，也不是食亨服务费收入；它更像经营收入中的费用扣减层。",
    tags: ["智慧门店", "营收看板", "经营", "支出"],
    relatedFieldIds: ["estimated-income", "gross-revenue", "smart-store-discount-amount", "smart-store-platform-service-fee"],
    toolRelevance: "medium",
    drill: ["拆看优惠、服务费、配送费、退款等明细", "确认统计日期与对比日期一致"],
  },
  {
    id: "smart-store-take-rate-confirm",
    name: "到手率（待确认）",
    category: "智慧门店",
    source: "食亨智慧门店 APP - 经营 - 营收 - 核心指标",
    summary: "截图中显示为百分比类指标，疑似用于观察收入扣减后商家最终可获得比例，字段名和口径待确认。",
    formula: "疑似口径：预计收入 / 营业额 x 100%，或扣减商家支出后的收入占比；需以 APP 字段说明或更清晰截图确认。",
    misread: "该字段目前待确认，不应直接用于财务结算或绩效口径，只适合先作为经营看板解释项。",
    tags: ["智慧门店", "营收看板", "经营", "待确认"],
    relatedFieldIds: ["estimated-income", "gross-revenue", "smart-store-merchant-expense"],
    toolRelevance: "low",
  },
  {
    id: "smart-store-pre-discount-order-average",
    name: "折前单均",
    category: "智慧门店",
    source: "食亨智慧门店 APP - 经营 - 营收 - 核心指标",
    summary: "优惠或折扣前，每笔有效订单对应的平均商品金额。",
    formula: "折前单均 = 折前口径金额 / 有效订单数，常用于观察客单结构在优惠前的原始水平。",
    misread: "折前单均不代表实际收入，促销优惠、退款和服务费会让它高于折后或预计收入口径。",
    tags: ["智慧门店", "营收看板", "经营", "订单"],
    relatedFieldIds: ["order-count", "gross-revenue", "smart-store-product-original-amount"],
    toolRelevance: "medium",
  },
  {
    id: "smart-store-post-discount-order-average",
    name: "折后单均",
    category: "智慧门店",
    source: "食亨智慧门店 APP - 经营 - 营收 - 核心指标",
    summary: "优惠或折扣后，每笔有效订单对应的平均金额。",
    formula: "折后单均 = 折后口径金额 / 有效订单数，通常低于或等于折前单均。",
    misread: "折后单均仍是经营观察口径，不等于银行卡到账或最终结算金额。",
    tags: ["智慧门店", "营收看板", "经营", "订单", "优惠"],
    relatedFieldIds: ["order-count", "net-revenue", "smart-store-pre-discount-order-average", "smart-store-discount-amount"],
    toolRelevance: "medium",
  },
  {
    id: "smart-store-pre-discount-customer-average",
    name: "折前人均",
    category: "智慧门店",
    source: "食亨智慧门店 APP - 经营 - 营收 - 核心指标",
    summary: "优惠或折扣前，平均每位就餐人数贡献的商品金额。",
    formula: "折前人均 = 折前口径金额 / 就餐人数；就餐人数为空或为 0 时该指标可能不可用。",
    misread: "折前人均受就餐人数填写准确性影响，不适合单独解释最终收入变化。",
    tags: ["智慧门店", "营收看板", "经营", "订单"],
    relatedFieldIds: ["smart-store-diner-count", "smart-store-product-original-amount", "smart-store-post-discount-order-average"],
    toolRelevance: "medium",
  },
  {
    id: "smart-store-average-ticket",
    name: "客单价",
    category: "智慧门店",
    source: "食亨智慧门店 APP - 经营 - 营收 - 核心指标",
    summary: "衡量单笔订单或单次消费的平均金额，是观察消费水平的经营指标。",
    formula: "常见口径为营业额 / 有效订单数，或按看板定义的订单收入 / 有效订单数计算。",
    misread: "客单价不是人均消费，也不是单笔到卡金额；它受订单数、优惠和退款口径影响。",
    tags: ["智慧门店", "营收看板", "经营", "订单"],
    relatedFieldIds: ["gross-revenue", "order-count", "smart-store-pre-discount-order-average"],
    toolRelevance: "medium",
  },
  {
    id: "smart-store-diner-count",
    name: "就餐人数",
    category: "智慧门店",
    source: "食亨智慧门店 APP - 经营 - 营收 - 核心指标",
    summary: "统计周期内订单记录的就餐人数汇总，用于计算人均类指标。",
    formula: "通常来自订单中的人数录入或桌台消费人数汇总，具体取值依赖门店实际录入。",
    misread: "就餐人数不一定等于订单数。若门店未录入人数或录入不完整，人均指标会失真。",
    tags: ["智慧门店", "营收看板", "经营", "订单"],
    relatedFieldIds: ["order-count", "smart-store-pre-discount-customer-average"],
    toolRelevance: "low",
  },
  {
    id: "smart-store-product-original-amount",
    name: "商品原价",
    category: "智慧门店",
    source: "食亨智慧门店 APP - 经营 - 营收 - 核心指标",
    summary: "商品按原价形成的金额合计，用于观察优惠前的商品销售规模。",
    formula: "商品原价 = 商品原始单价 x 数量的汇总，通常不扣除优惠、退款、服务费或配送费。",
    misread: "商品原价不是营业额的绝对等价字段，也不是预计收入；是否包含套餐、加料或改价需按看板口径确认。",
    tags: ["智慧门店", "营收看板", "经营", "订单"],
    relatedFieldIds: ["gross-revenue", "smart-store-discount-amount", "smart-store-pre-discount-order-average"],
    toolRelevance: "medium",
  },
  {
    id: "smart-store-packing-fee",
    name: "打包费",
    category: "智慧门店",
    source: "食亨智慧门店 APP - 经营 - 营收 - 核心指标",
    summary: "订单中因打包或餐盒产生的费用合计，通常用于外带、外卖或自提场景。",
    formula: "打包费 = 订单内打包费项目汇总，可能按商品、订单或门店规则收取。",
    misread: "打包费不一定参与商品原价，也不一定都进入预计收入，需结合平台和门店费用归属口径确认。",
    tags: ["智慧门店", "营收看板", "经营", "支出"],
    relatedFieldIds: ["gross-revenue", "estimated-income", "smart-store-merchant-expense"],
    toolRelevance: "medium",
  },
  {
    id: "smart-store-self-delivery-fee",
    name: "自配送费",
    category: "智慧门店",
    source: "食亨智慧门店 APP - 经营 - 营收 - 核心指标",
    summary: "门店自行配送场景下产生的配送费金额。",
    formula: "自配送费通常来自订单配送费字段汇总，可能按距离、门店规则或订单金额计算。",
    misread: "自配送费与平台配送费、商家承担配送补贴不是同一个口径，解释差异时要先确认配送方式。",
    tags: ["智慧门店", "营收看板", "经营", "支出"],
    relatedFieldIds: ["gross-revenue", "estimated-income", "smart-store-merchant-expense"],
    toolRelevance: "medium",
  },
  {
    id: "smart-store-discount-amount",
    name: "优惠金额",
    category: "智慧门店",
    source: "食亨智慧门店 APP - 经营 - 营收 - 核心指标",
    summary: "统计周期内订单享受的优惠合计，会影响折前和折后金额差异。",
    formula: "优惠金额通常由商家优惠、平台活动、券、满减等折扣项汇总，承担方需按看板口径确认。",
    misread: "优惠金额不一定全部由商家承担。若平台补贴和商家承担混在一起，会导致预计收入解释偏差。",
    tags: ["智慧门店", "营收看板", "经营", "优惠", "支出"],
    relatedFieldIds: ["net-revenue", "refund-amount", "smart-store-merchant-expense"],
    toolRelevance: "medium",
  },
  {
    id: "smart-store-platform-service-fee",
    name: "平台服务费",
    category: "智慧门店",
    source: "食亨智慧门店 APP - 经营 - 营收 - 核心指标",
    summary: "平台侧按订单或交易规则收取的服务费用，影响商家预计收入。",
    formula: "平台服务费通常按平台规则、费率或订单服务项目计算，并在营收看板中作为支出或扣减项展示。",
    misread: "平台服务费不是本工具中的品牌抽佣，也不等同于食亨外卖接单费；三者发生主体和扣减层级不同。",
    tags: ["智慧门店", "营收看板", "经营", "支出", "服务费/佣金"],
    relatedFieldIds: ["takeout-order-fee", "platform-commission-rate", "smart-store-merchant-expense"],
    toolRelevance: "medium",
  },
  {
    id: "smart-store-gift-amount",
    name: "赠送金额",
    category: "智慧门店",
    source: "食亨智慧门店 APP - 经营 - 营收 - 核心指标",
    summary: "订单中赠送、免单或赠品类优惠形成的金额。",
    formula: "赠送金额通常按赠送商品、赠送活动或免收金额汇总，具体是否计入优惠金额需按看板定义确认。",
    misread: "赠送金额会影响经营分析，但不代表实际收款损失一定等额发生，需要看活动承担方和核算口径。",
    tags: ["智慧门店", "营收看板", "经营", "优惠"],
    relatedFieldIds: ["net-revenue", "refund-amount", "smart-store-discount-amount"],
    toolRelevance: "low",
  },
];
